// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcI6_0I4wUZiPVflVeqtbScr4g9-fSxEk',
    appId: '1:575863172937:web:8b495be466fb0868747498',
    messagingSenderId: '575863172937',
    projectId: 'smart-greenhouse-ea672',
    authDomain: 'smart-greenhouse-ea672.firebaseapp.com',
    storageBucket: 'smart-greenhouse-ea672.appspot.com',
    databaseURL: 'https://smart-greenhouse-ea672-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kiGq3HHOkiLoO3j9uEyRRNiZGgjRFkY',
    appId: '1:575863172937:android:36a6d3021c7c58d4747498',
    messagingSenderId: '575863172937',
    projectId: 'smart-greenhouse-ea672',
    storageBucket: 'smart-greenhouse-ea672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJGI9zI2q4cK2e-nb0IUrhuk1BmYqXwQ',
    appId: '1:575863172937:ios:9000f8640ac02d17747498',
    messagingSenderId: '575863172937',
    projectId: 'smart-greenhouse-ea672',
    storageBucket: 'smart-greenhouse-ea672.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJGI9zI2q4cK2e-nb0IUrhuk1BmYqXwQ',
    appId: '1:575863172937:ios:45867f33b3987e21747498',
    messagingSenderId: '575863172937',
    projectId: 'smart-greenhouse-ea672',
    storageBucket: 'smart-greenhouse-ea672.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
